### ISSUE TITLE
Import/Export options don't appear to work.

### ISSUE THREAD

**Issue by SneakyDave** [VersoBit/XF-Badges#14]
Not sure what the deal is with this, but I don't have the addon installed anymore.  I reported it on xenforo a year ago.
https://xenforo.com/community/threads/badges.169672/#post-1380130

**Comment by RyleaStark** [comment]
Duplicate of #11

**Comment by RyleaStark** [comment]
Duplicate of #12

**Comment by RyleaStark** [comment]
@SneakyDave The original developer never coded these functions in, he did however template the ACP classes which is why it never worked. Planned updates!!
