### ISSUE TITLE
CSS flex instead of grid for featuredBadges class

### ISSUE THREAD

**Issue by KaliszS** [VersoBit/XF-Badges#15]
This is how the last row of featured badges could be centered.

**Example of Current View**:
![image](https://user-images.githubusercontent.com/5894962/99296259-b3b61680-2803-11eb-9e92-c4a347f383f6.png)

**Affected lines of code**: https://github.com/VersoBit/XF-Badges/blob/8f85e673be67159e94504d1bc7350ae8d0f3229c/_output/templates/public/CMTV_Badges_featured_badges.less#L8

**Solution**: https://xenforo.com/community/threads/badges.169672/page-4#post-1469403

**Suggested Edit**: 
```
    display: flex;
    flex-wrap: wrap;
```
**Example of Suggested Edit**:
![image](https://user-images.githubusercontent.com/5894962/99296272-b7e23400-2803-11eb-8be3-13307049b6d6.png)

**Comment by RyleaStark** [comment]
Thanks for this @KaliszS; It makes more sense visually to have these centered in this element. Will apply in next release.
